# Generated by Django 5.2.7 on 2025-10-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='renovado',
            field=models.BooleanField(default=False),
        ),
    ]
