# Generated by Django 5.2.7 on 2025-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
