# Generated by Django 5.2.7 on 2025-11-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
