# Generated by Django 5.2.7 on 2025-11-05 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('avatares/default.jpg', 'Por Defecto'), ('avatares/capitan.jpg', 'Capitán'), ('avatares/capitana.jpg', 'Capitana'), ('avatares/investigador.jpg', 'Investigador'), ('avatares/investigadora.jpg', 'Investigadora'), ('avatares/hombre_blanco.jpg', 'Lector (HB)'), ('avatares/mujer_blanca.jpg', 'Lectora (MB)'), ('avatares/hombre_negro.jpg', 'Lector (HN)'), ('avatares/mujer_negra.jpg', 'Lectora (MN)')], default='avatares/default.jpg', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
