# Generated by Django 5.2.7 on 2025-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(choices=[('avatares/default.png', 'Por Defecto'), ('avatares/capitan.png', 'Capitán'), ('avatares/capitana.png', 'Capitana'), ('avatares/investigador.png', 'Investigador'), ('avatares/investigadora.png', 'Investigadora'), ('avatares/hombre_blanco.png', 'Lector (HB)'), ('avatares/mujer_blanca.png', 'Lectora (MB)'), ('avatares/hombre_negro.png', 'Lector (HN)'), ('avatares/mujer_negra.png', 'Lectora (MN)')], default='avatares/default.png', max_length=100),
        ),
    ]
