# Generated by Django 5.2.7 on 2025-11-05 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_perfil_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('publicado', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(default='Documento', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('formato', models.CharField(default='Físico', max_length=50)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.material'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.material'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.material'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('libro__isnull', False), ('material__isnull', True)), models.Q(('libro__isnull', True), ('material__isnull', False)), _connector='OR'), name='favorito_libro_o_material_no_ambos'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('libro__isnull', False), ('material__isnull', True)), models.Q(('libro__isnull', True), ('material__isnull', False)), _connector='OR'), name='prestamo_libro_o_material_no_ambos'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('libro__isnull', False), ('material__isnull', True)), models.Q(('libro__isnull', True), ('material__isnull', False)), _connector='OR'), name='reserva_libro_o_material_no_ambos'),
        ),
    ]
