# Generated by Django 5.2.7 on 2025-11-11 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Número de copias disponibles en total.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Número de copias disponibles en total.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
