# Generated by Django 5.2.7 on 2025-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_libro_cantidad_material_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
