# Generated by Django 5.2.7 on 2025-11-23 17:54

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_noticia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorito',
            name='favorito_libro_o_material_no_ambos',
        ),
        migrations.RemoveConstraint(
            model_name='prestamo',
            name='prestamo_libro_o_material_no_ambos',
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='reserva_libro_o_material_no_ambos',
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_retiro',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='clave',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(default='Documento', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'En Lista de Espera'), ('PENDIENTE_RETIRO', 'Listo para Retiro'), ('COMPLETADA', 'Entregado (Prestamo)'), ('CANCELADA', 'Cancelada / No Retirado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('libro__isnull', False), ('material__isnull', True)), models.Q(('libro__isnull', True), ('material__isnull', False)), _connector='OR'), name='prestamo_libro_o_material'),
        ),
    ]
